<?php
$section  = 'site_skin';
$priority = 1;

Kirki::add_field( 'thememove', array(
	'type'        => 'preset',
	'settings'    => 'preset',
	'description' => esc_html__( 'Choose a preset you want', 'tm-heli' ),
	'label'       => esc_html__( 'Preset', 'tm-heli' ),
	'section'     => $section,
	'default'     => '1',
	'priority'    => $priority ++,
	'multiple'    => 3,
	'choices'     => array(
		'1'  => array(
			'label'    => esc_html__( 'Preset 1', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header01',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'2'  => array(
			'label'    => esc_html__( 'Preset 2', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header02',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'3'  => array(
			'label'    => esc_html__( 'Preset 3', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header03',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'4'  => array(
			'label'    => esc_html__( 'Preset 4', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header04',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'5'  => array(
			'label'    => esc_html__( 'Preset 5', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header01',
				'top_slider_enable'                => 1,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'6'  => array(
			'label'    => esc_html__( 'Preset 6', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header04',
				'top_slider_enable'                => 1,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'7'  => array(
			'label'    => esc_html__( 'Preset 7', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header05',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'8'  => array(
			'label'    => esc_html__( 'Preset 8', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header02',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => '#fff',
				'main_menu_hover_color'            => '#fff',
				'minicart_icon_color'              => '#fff',
				'minicart_number_bg'               => '#fff',
				'minicart_number_color'            => TM_HELI_PRIMARY_COLOR,
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'9'  => array(
			'label'    => esc_html__( 'Preset 9', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header02',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => '#fff',
				'main_menu_hover_color'            => '#fff',
				'minicart_icon_color'              => '#fff',
				'minicart_number_bg'               => '#fff',
				'minicart_number_color'            => TM_HELI_PRIMARY_COLOR,
				'header_bg'                        => 'rgba(0,0,0,1)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'10' => array(
			'label'    => esc_html__( 'Preset 10', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header05',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => '#fff',
				'main_menu_hover_color'            => '#fff',
				'minicart_icon_color'              => '#fff',
				'minicart_number_bg'               => '#fff',
				'minicart_number_color'            => TM_HELI_PRIMARY_COLOR,
				'header_bg'                        => 'rgba(0,0,0,1)',
				'nav_level_1_bg'                   => '#000',
				'footer_enable'                    => 0,
				'copyright_enable'                 => 0,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'11' => array(
			'label'    => esc_html__( 'Preset 11', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header06',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'12' => array(
			'label'    => esc_html__( 'Preset 12', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header07',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => '#fff',
				'main_menu_hover_color'            => '#fff',
				'minicart_icon_color'              => '#fff',
				'minicart_number_bg'               => '#fff',
				'minicart_number_color'            => TM_HELI_PRIMARY_COLOR,
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 1,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'13' => array(
			'label'    => esc_html__( 'Preset 13', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header08',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 0,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'14' => array(
			'label'    => esc_html__( 'Preset 14', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header01',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 0,
				'copyright_enable'                 => 0,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'15' => array(
			'label'    => esc_html__( 'Preset 15', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 0,
				'header_type'                      => 'header01',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => TM_HELI_PRIMARY_COLOR,
				'main_menu_hover_color'            => TM_HELI_PRIMARY_COLOR,
				'minicart_icon_color'              => TM_HELI_PRIMARY_COLOR,
				'minicart_number_bg'               => TM_HELI_PRIMARY_COLOR,
				'minicart_number_color'            => '#fff',
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 0,
				'copyright_enable'                 => 0,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'16' => array(
			'label'    => esc_html__( 'Preset 16', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header09',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => '#fff',
				'main_menu_hover_color'            => '#fff',
				'minicart_icon_color'              => '#fff',
				'minicart_number_bg'               => '#fff',
				'minicart_number_color'            => TM_HELI_PRIMARY_COLOR,
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 0,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-01',
				'copyright_style_bg_color'         => '#fff',
				'copyright_style_text_color'       => '#222',
				'copyright_style_link_color'       => '#222',
				'copyright_style_link_color_hover' => '#222'
			),
		),
		'17' => array(
			'label'    => esc_html__( 'Preset 17', 'tm-heli' ),
			'settings' => array(
				'header_enable'                    => 1,
				'header_type'                      => 'header10',
				'top_slider_enable'                => 0,
				'main_menu_color'                  => '#222',
				'main_menu_hover_color'            => '#222',
				'minicart_icon_color'              => '#222',
				'minicart_number_bg'               => '#222',
				'minicart_number_color'            => TM_HELI_PRIMARY_COLOR,
				'header_bg'                        => 'rgba(0,0,0,0)',
				'footer_enable'                    => 0,
				'copyright_enable'                 => 1,
				'copyright_type'                   => 'copyright-03',
				'copyright_style_bg_color'         => '#222',
				'copyright_style_text_color'       => '#fff',
				'copyright_style_link_color'       => '#fff',
				'copyright_style_link_color_hover' => '#fff'
			),
		)
	),
) );
