<?php
vc_map( array(
	'name'     => esc_html__( 'TM Price Box', 'tm-heli' ),
	'base'     => 'thememove_pricing_box',
	'category' => sprintf( esc_html__( 'by %s', 'tm-heli' ), TM_HELI_PARENT_THEME_NAME ),
	'params'   => array(
		array(
			'type'        => 'textfield',
			'class'       => '',
			'heading'     => esc_html__( 'Package Name', 'tm-heli' ),
			'param_name'  => 'package_heading',
			'admin_label' => true,
			'value'       => '',
			'description' => esc_html__( 'Enter the package name or table heading', 'tm-heli' ),
		),
		array(
			'type'        => 'textfield',
			'class'       => '',
			'heading'     => esc_html__( 'Sub Heading', 'tm-heli' ),
			'param_name'  => 'package_sub_heading',
			'value'       => '',
			'description' => esc_html__( 'Enter short description for this package', 'tm-heli' ),
		),
		array(
			'type'        => 'textfield',
			'class'       => '',
			'heading'     => esc_html__( 'Package Price', 'tm-heli' ),
			'param_name'  => 'package_price',
			'value'       => '',
			'description' => esc_html__( 'Enter the price for this package. e.g. $99', 'tm-heli' ),
		),
		array(
			'type'        => 'textfield',
			'class'       => '',
			'heading'     => esc_html__( 'Price Unit', 'tm-heli' ),
			'param_name'  => 'package_unit',
			'value'       => '',
			'description' => esc_html__( 'Enter the price unit for this package. e.g. per month', 'tm-heli' ),
		),
		array(
			'type'        => 'attach_image',
			'heading'     => esc_html__( 'Package Image', 'tm-heli' ),
			'param_name'  => 'package_image',
			'admin_label' => false,
		),
		array(
			'type'             => 'textarea_html',
			'class'            => '',
			'heading'          => esc_html__( 'Features', 'tm-heli' ),
			'param_name'       => 'content',
			'value'            => '',
			'description'      => esc_html__( 'Create the features list using un-ordered list elements.', 'tm-heli' ),
			'edit_field_class' => 'ult_hide_editor_fullscreen vc_col-xs-12 vc_column wpb_el_type_textarea_html vc_wrapper-param-type-textarea_html vc_shortcode-param',
		),
		array(
			'type'        => 'textfield',
			'class'       => '',
			'heading'     => esc_html__( 'Button Text', 'tm-heli' ),
			'param_name'  => 'package_btn_text',
			'value'       => '',
			'description' => esc_html__( 'Enter call to action button text', 'tm-heli' ),
		),
		array(
			'type'        => 'vc_link',
			'class'       => '',
			'heading'     => esc_html__( 'Button Link', 'tm-heli' ),
			'param_name'  => 'package_link',
			'value'       => '',
			'description' => esc_html__( 'Select / enter the link for call to action button', 'tm-heli' ),
		),
		array(
			'type'       => 'checkbox',
			'class'      => '',
			'heading'    => '',
			'param_name' => 'package_featured',
			'value'      => array( 'Featured Price Box' => 'enable' ),
		),
		array(
			'type'        => 'textfield',
			'heading'     => esc_html__( 'Extra class name', 'tm-heli' ),
			'param_name'  => 'el_class',
			'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'tm-heli' ),
		),
	),
) );
